checked_weapons:
    list:
    - 267
    - 268
    - 272
    - 276
    - 283
checked_armor:
    list:
    - 298
    - 299
    - 300
    - 301
string:
    weapon: "You don't have the needed permissions to use this weapon"
    helmet: "You don't have the needed permissions to wear this helmet"
    chest: "You don't have the needed permissions to wear this chestplate"
    leggings: "You don't have the needed permissions to wear this leggings"
    boots: "You don't have the needed permissions to wear this boots"
    