name: EquipControl
main: de.syd.equipcontrol.EquipControl
version: 0.2
description: Limit Weapons and Armor
author: SydMontague
dev-url: http://dev.bukkit.org/server-mods/equipcontrol/
permissions:
    equipcontrol.weapon.<id>:
        default: false
    equipcontrol.weapon.<material>:
        default: false
    equipcontrol.armor.<id>:
        default: false
    equipcontrol.armor.<material>:
        default: false
    